### PR TITLE
Coin control

### PR DESCRIPTION
**Pull request by sigmike**
I imported Coin control from Nu 2.1 (because it already included peerunity and peercoin/develop), and then applied a few coin control related patches I could find.

I tested it on testnet and it seemed to work fine.

### CODE REVIEW

**Comment by hrobeers** [comment]
I get these signal connection errors:

```
Object::connect: No such signal OptionsModel::transactionFeeChanged(qint64)
Object::connect:  (receiver name: 'SendCoinsDialog')
```

**Comment by sigmike** [comment]
Indeed I missed it. It's fixed now, but this option to change the fee should really be removed.

**Comment by hrobeers** [comment]
Looks good to me, the option to change the fee is not available through the UI as far as I can see so not really a problem.

I'll merge this because people are waiting on this.

**Comment by sigmike** [comment]
> the option to change the fee is not available through the UI

It's in the options dialog.

**Pull request merged**
