### PR TITLE
Hardened checkpoint update for v0.14.0 testnet

### PR DESCRIPTION
**Pull request by sandakersmann**
Hardened checkpoint update for v0.14.0 testnet

### CODE REVIEW

**Comment by sandakersmann** [comment]
@backpacker69 Please merge :)

**Comment by backpacker69** [comment]
please create request for release-0.14, not master

**Comment by sandakersmann** [comment]
@backpacker69 Done :)

**Comment by backpacker69** [comment]
merged into release-0.14

**Pull request closed without merging**
