### PR TITLE
[issue#202] Helpful Help menu links to chat and forum.

### PR DESCRIPTION
**Pull request by belovachap**
hallo peercoin people! @peerchemist @backpacker69 @Sentinelrv 

This idea: https://github.com/peercoin/peercoin/issues/202

A couple of menu items in the Help menu that will open peercoin chat / forum :) I grabbed the "external_link" icon from wiki commons ( https://commons.wikimedia.org/wiki/File:External_link_icon.png ) as a stand-in ... although i kind of like the little globe :earth_africa:

### CODE REVIEW

**Comment by belovachap** [comment]
Hi there @hrobeers :) :wave: 

I was following along with the instructions in https://github.com/peercoin/peercoin/blob/master/doc/translation_process.md#bitcoin_ents-source-file

I'm not entirely sure when the other locales' .ts files are updated... we could run the command `lupdate bitcoin-qt.pro -no-obsolete -locations relative` to have all the .ts files update. You wouldn't happen to know what the translation process should look like do you? Seems like the process bitcoin used/uses isn't what we're using?

**Comment by hrobeers** [comment]
I like that little globe more too
The icon is really ugly IMO.

**Comment by belovachap** [comment]
Oh, if we don't like the icon perhaps we could just leave that out entirely? Alternatively, there's a little "peercoin leaf" icon for `Help > About Peercoin` we could reuse.

**Comment by Sentinelrv** [comment]
You can use our favicon for both...

https://github.com/peercoin/media/blob/master/Peercoin%202016%20Logo%20Files/06.%20Favicons/Icon/16x16/favicon.png

**Comment by hrobeers** [comment]
I like the leaf!
Would you mind rewriting your PR so the discarded logo won't pollute our git?
```
git reset --soft <git-hash-before-3f124d7>
git commit -m <new-message>
git push -f
```

**Comment by belovachap** [comment]
@hrobeers you bet, I'll clean it up when I get back to my personal laptop (might be tomorrow, but sooooon) :)

**Comment by hrobeers** [comment]
Not in a hurry, take your time ;)

**Pull request merged**
