### PR TITLE
Fixes for when listtransactions encounters non-standard outputs

### PR DESCRIPTION
**Pull request by hrobeers**
backport from: https://github.com/bitcoin/bitcoin/pull/1850
should fix: https://github.com/peercoin/peercoin/issues/185

### CODE REVIEW

**Comment by hrobeers** [comment]
I've checked output[0] of that transaction.
The only info I can give about that output is that it is "non-standard".
"immature", "stake" or"orphan" are just wrong.

The output has an empty output script which makes no sense at all.
"send" is not wrong as it send it's value to an empty script.

@bananenwilly 
How was this transaction created? I wonder if it would get propagated on mainnet, I believe it will never work. You should file a bug report in the software that created this transaction.

**Comment by hrobeers** [comment]
Apparently the first output of the coinstake transaction is made empty.
Not sure this is needed,
https://github.com/peercoin/peercoin/blob/develop/src/wallet.cpp#L1390

I don't like it being highlighted as "immature" because that is incorrect.

I will merge this PR already and will open a new issue about the empty output.

**Comment by bananenwilly** [comment]
> I don't like it being highlighted as "immature" because that is incorrect.

Mh. That's the nomenclature from the QT. 

As I mentioned in a private chat earlier, I'm worried about the headless user experience, since the minted blocks are not displayed the same way as in qt ("stake/immature/orphan").

**Comment by hrobeers** [comment]
Yes you are right.
More investigation revealed only coinstake transactions are allowed to have empty outputs by the protocol.

More information about the state of the coinstake transaction can indeed be provided.
I will reopen https://github.com/peercoin/peercoin/issues/185
And I'll close https://github.com/peercoin/peercoin/issues/249

**Pull request merged**
