### PR TITLE
Possible fix for not building against boost >= 1.67

### PR DESCRIPTION
**Pull request by sandakersmann**
I have not tested this in any way and I'm not sure if it will work. Please do a full review and testing before merging.

### CODE REVIEW

**Comment by sandakersmann** [comment]
Possible fix for this issue:

https://github.com/peercoin/peercoin/issues/380

**Comment by sandakersmann** [comment]
@peerchemist I have another idea as well if this does not work.

**Comment by peerchemist** [comment]
Will test as soon as I get access to my ArchLinux machine.

**Comment by peerchemist** [comment]
Configure will still fail with `configure: error: No working boost sleep implementation found`

**Comment by sandakersmann** [comment]
Let's try the other idea.

**Pull request closed without merging**
