### PR TITLE
Update init.cpp

### PR DESCRIPTION
**Pull request by imharrywu**
failed to build with mingw( cross compiling on ubuntu 14.04 for windows)

### CODE REVIEW

**Comment by hrobeers** [comment]
@backpacker69 any idea why the travis-ci build fails?

**Comment by linalouise9** [comment]
@imharrywu Please update your patch to by in synch with the latest develop branch.

The build fails because an outdated develop branch is being used, which is using outdated travis build.

There should be a build matrix, instead travis only shows a single build. Meaning the pull request branch is not up to date.

**Comment by imharrywu** [comment]
sorry for the wrong post, i have not synced yet. i will post a patch with synced version later.

**Comment by hrobeers** [comment]
@linalouise9 Thanks for clarification.
I will merge this change as it is very simple, and shouldn't break the build.

**Pull request merged**
