### PR TITLE
enable-mining/disable-mining flag to toggle mining and minting…

### PR DESCRIPTION
**Pull request by hrobeers**
… code for virus scanners

### CODE REVIEW

**Comment by peerchemist** [comment]
Perhaps minting tab should be disabled in the QT client when this flag is set, as it could Beverly confuse the user. We'll serve binaries with this flag set to least experienced and least technical band of users.

**Comment by backpacker69** [comment]
according to virustotal not much has changed, do we have anyone with windows defender to run tests?

**Comment by peerchemist** [comment]
https://www.virustotal.com/

**Comment by backpacker69** [comment]
that's what i meant, virustotal does not show any differences.

**Comment by peerchemist** [comment]
Could it be just lack of signature on the binary?

**Comment by hrobeers** [comment]
Yes some virus scanners require signed binaries.

I will work on disabling the minting tab too.
to be continued ...

**Comment by hrobeers** [comment]
@peerchemist @backpacker69 The minting tab is now hidden when compiled using --disable-mining

**Comment by peerchemist** [comment]
Works as expected, it disables the minting and removes the minting tab.
We'll need someone with the Windows OS machine to test it once again.

**Pull request merged**
