### PR TITLE
Replace Bitcoin with Peercoin in cyrillic

### PR DESCRIPTION
**Pull request by sandakersmann**
Peercoin: Пееркоин
Bitcoin: Биткоин

### CODE REVIEW

**Comment by peerchemist** [comment]
I got corrected in the meantime.

`пиркойн`

Because `i` is `ee`.

**Comment by sandakersmann** [comment]
Are you sure about that correction? Google translate does not seem to agree.

**Comment by sandakersmann** [comment]
How about `Пиркоин`?

**Comment by backpacker69** [comment]
does Google find many results for биткоин?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sandakersmann** [comment]
10 100 000 results

**Comment by sandakersmann** [comment]
2 170 000 results for `биткойн`

**Comment by backpacker69** [comment]
wow. but rules for russian language together with wikipedia do not agree. if 10m idiots write incorrectly, does it mean we have to correct the language?

it is supposed to be written as пиркойн.

**Comment by sandakersmann** [comment]
Thanks, I will make a new pull with `Пиркойн` then :)

**Comment by backpacker69** [comment]
but i wonder if bulgarian language rules are different )

**Comment by sandakersmann** [comment]
Bitcoin was the same in both locales.

**Pull request closed without merging**
