### PR TITLE
A potential fix for the weird send entries layout.

### PR DESCRIPTION
**Pull request by belovachap**
The changes in `sendcoinsentry.ui` came from Qt Designer, I changed the vertical sizing policy to "Fixed" so the send entries wouldn't try to expand vertically.

The changes in `sendcoinsdialog.cpp` are making the `VBoxLayout` `entries` put the entries at the top of the layout, otherwise it was putting it in the center of the page. I wanted to set the alignment in Qt Designer but it wasn't available for some reason :\

image

### CODE REVIEW

**Comment by peerchemist** [comment]
I've tested it and it looks exactly the same as it did before with this patch.

**Comment by belovachap** [comment]
oh, bummer... are you using qt4 or 5? i only looked at it in qt5 :\

**Comment by peerchemist** [comment]
QT5 of course.

**Comment by belovachap** [comment]
Should work a little better with coin control now:
image

**Pull request merged**
