### PR TITLE
Fix invalid signature with crafted length

### PR DESCRIPTION
**Pull request by sigmike**
First draft to fix issue #100

### CODE REVIEW

**Comment by rat4** [comment]
The patch has a flaw: a specifically crafted signature may cause invalid memory access because existence of nExtraBytes ain't checked.

**Comment by sigmike** [comment]
Indeed. I pushed a fix. Do you agree it solves the problem?

**Comment by rat4** [comment]
Yes, it does.

**Comment by sandakersmann** [comment]
I think this pull can be closed.

**Pull request closed without merging**
