### PR TITLE
Replace more Bitcoin in cyrillic with Peercoin

### PR DESCRIPTION
**Pull request by sandakersmann**
Replace more Bitcoin in cyrillic with Peercoin

### CODE REVIEW

**Comment by peerchemist** [comment]
Why not "Peercoin" in cyrillic?

**Comment by sandakersmann** [comment]
Don't know how to do that and I got no answer in the forum. The Russian guy that made changes to the Russian locale did also use Peercoin.

**Comment by hrobeers** [comment]
I approve, I have no opinion on Peercoin in cyrillic or latin.
So feel free to merge if everyone agrees.

**Comment by peerchemist** [comment]
@sandakersmann 

it's "Пееркоин".
I used http://www.lexilogos.com/keyboard/russian_conversion.htm and verified against our russian speaking community members.

**Comment by sandakersmann** [comment]
@peerchemist Thanks:) Made a new pull.

**Pull request closed without merging**
