### PR TITLE
Hardened checkpoint update for v0.11.0 mainnet

### PR DESCRIPTION
**Pull request by sandakersmann**
Hardened checkpoint update for v0.11.0 mainnet

### CODE REVIEW

**Comment by backpacker69** [comment]
let's wait for first block with v3 transaction first

**Comment by sandakersmann** [comment]
@backpacker69 Please merge :)

**Comment by sandakersmann** [comment]
> let's wait for first block with v3 transaction first

ok

**Comment by backpacker69** [comment]
like i said, we need to wait for v3 transaction first and have the block with it as checkpoint

**Comment by backpacker69** [comment]
we have block with v3 transactions now, block 967c14abf21214639aeff0a270c4543cd3b80fe53178384ac5aa3c277662f1d0

**Pull request closed without merging**
