### PR TITLE
Wallet Redesign

### PR DESCRIPTION
**Pull request by captainbuckkets**
New style + icons for the QT wallet

### CODE REVIEW

**Comment by captainbuckkets** [comment]
Was told to push to dev

**Comment by sandakersmann** [comment]
Does Roboto-Regular.ttf support all languages, like Cyrillic for example?

**Comment by captainbuckkets** [comment]
https://fonts.google.com/specimen/Roboto

My assumption was yes because it’s a google font and there is a chart that indicates Russian usage.

**Comment by captainbuckkets** [comment]
I saw Greek and Cyrillic support on Wikipedia as well. https://en.m.wikipedia.org/wiki/Roboto

**Comment by sandakersmann** [comment]
"Noto is a font family comprising over a hundred individual fonts, which are together designed to cover all the scripts encoded in the Unicode standard."

https://en.wikipedia.org/wiki/Noto_fonts

**Comment by sandakersmann** [comment]
> I saw Greek and Cyrillic support on Wikipedia as well. https://en.m.wikipedia.org/wiki/Roboto

From your link: "On Android, the Noto font is used for languages not covered by Roboto"

**Comment by sandakersmann** [comment]
So it looks like we have to use Noto...

**Comment by captainbuckkets** [comment]
What was the original font that caused the issue?

**Comment by captainbuckkets** [comment]
If you can teach me how to deploy it in Russian I will check it. Says it’s fully supported

**Comment by peerchemist** [comment]
> If you can teach me how to deploy it in Russian I will check it. Says it’s fully supported

You need to apply for Russian visa to do that.

**Comment by sandakersmann** [comment]
> What was the original font that caused the issue?

WeblySleek.ttf


> If you can teach me how to deploy it in Russian I will check it. Says it’s fully supported

I'm not only worried about Russian. I also don't see why we need to change the font.

**Comment by captainbuckkets** [comment]
Because Roboto is one of the standardized fonts for Peercoin. We use FF mark and Roboto.

**Comment by captainbuckkets** [comment]
Is it not possible to include Roboto as he primary with Noto as the backup?

**Comment by sandakersmann** [comment]
Maybe we should change the standard to Noto then.

**Comment by captainbuckkets** [comment]
No haha. Noto is ugly. Website + all other branded places should be using the same font which represents the brand. This has wide system support and there should be no issues

**Comment by sandakersmann** [comment]
> No haha. Noto is ugly. Website + all other branded places should be using the same font which represents the brand. This has wide system support and there should be no issues

I'm sure NotoSans-Regular.ttf supports more languages since it is 455 kB.
Roboto-Regular.ttf is 171 kB.

**Comment by captainbuckkets** [comment]
Alright then. Can you revert it until I find an acceptable work around?

**Comment by captainbuckkets** [comment]
Reverted.  Please leave the Roboto.ttf there for future implementation.

**Comment by sandakersmann** [comment]
Looks good to me, but I have not tested this in any way.

**Pull request closed without merging**
