### PR TITLE
Hardened checkpoint update for v0.9.1 mainnet

### PR DESCRIPTION
**Pull request by sandakersmann**
Hardened checkpoint update for v0.9.1 mainnet

### CODE REVIEW

**Comment by sandakersmann** [comment]
@backpacker69 @peerchemist Added a new checkpoint. Please merge :)

**Comment by sandakersmann** [comment]
@backpacker69 Should I push this to peercoin-0.20 instead?

**Comment by peerchemist** [comment]
No leave it on this branch.

**Comment by sandakersmann** [comment]
@backpacker69 Can you merge this to v0.10.0?

**Comment by peerchemist** [comment]
Yes can you please move the PR to that branch.

**Pull request closed without merging**
